#ifndef NSRREADERCORE_GLOBAL_H_
#define NSRREADERCORE_GLOBAL_H_

#include <qglobal.h>

#ifdef NSRREADERCORE_LIBRARY
#  define NSRREADERCORE_SHARED	Q_DECL_EXPORT
#else
#  define NSRREADERCORE_SHARED	Q_DECL_IMPORT
#endif

#endif /* NSRREADERCORE_GLOBAL_H_ */
